# Generated by Django 3.2.12 on 2024-04-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='identity',
            name='attribute',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='identity',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
