# Generated by Django 3.2.12 on 2024-04-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0002_auto_20240413_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
